// Validation report for the Marquis opiate-screen profile:
//   docs/validation/kit_marquis_v1.md
//
//   node scripts/validate-kit.ts
//
// Part 1 (the main part) is REAL photos only: what the app says for every
// photo in data/real/mat/ that passes the card stage. Part 2 compares the
// published colours with each other. Part 3 is SYNTHETIC and labelled so:
// rendered cards with a patch of each published colour in the zone.

import { execSync } from 'node:child_process';
import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join, relative } from 'node:path';
import { analyseMat } from '../src/pipeline/analyse.ts';
import { ciede2000 } from '../src/pipeline/ciede2000.ts';
import { labToSrgb8, srgb8ToLab, type Vec3 } from '../src/pipeline/colour.ts';
import { classify, parseKitProfile } from '../src/pipeline/kit.ts';
import type { Mat3 } from '../src/pipeline/linalg.ts';
import { combineRegistration, REFERENCE_SCHEMA, type MatReference } from '../src/pipeline/reference.ts';
import { readSampleZone } from '../src/pipeline/samplezone.ts';
import { canonicalJson } from '../src/records/canonical.ts';
import { sha256HexOf } from '../src/records/webcrypto.ts';
import { parseCaptureName } from '../src/io/dataset.ts';
import { placement, renderPhoto } from '../tests/helpers/synth-card.ts';
import { loadCapture } from './lib/capture-files.ts';
import { loadReferences } from './lib/references.ts';

const PROFILE = 'profiles/kit_marquis_opiates_v1.json';
const OUT = 'docs/validation/kit_marquis_v1.md';
const profile = parseKitProfile(JSON.parse(readFileSync(PROFILE, 'utf8')));
const profileSha = await sha256HexOf(new TextEncoder().encode(canonicalJson(profile)));
const targets = profile.outcomes.flatMap((o) => o.targets);
const f1 = (v: number) => v.toFixed(1);
const lab = (v: readonly number[] | undefined | null) => (v ? v.map((x) => x.toFixed(1)).join(', ') : '—');

function listPngs(dir: string): string[] {
  if (!existsSync(dir)) return [];
  const out: string[] = [];
  for (const e of readdirSync(dir, { withFileTypes: true })) {
    const p = join(dir, e.name);
    if (e.isDirectory()) out.push(...listPngs(p));
    else if (e.name.endsWith('.png')) out.push(p);
  }
  return out.sort();
}

const L: string[] = [];
const commit = execSync('git rev-parse --short=12 HEAD').toString().trim();
L.push('# Marquis opiate screen (kit profile v1) — validation');
L.push('');
L.push(`Generated by \`scripts/validate-kit.ts\` at commit \`${commit}\` on ${new Date().toISOString().slice(0, 10)}. Profile \`${PROFILE}\`, profileSha256 \`${profileSha}\`.`);
L.push('');
L.push(`**${profile.validationLine}.** Validation status: \`${profile.validation}\`.`);
L.push('');
L.push('## 1. Real photos (the only real evidence)');
L.push('');
L.push('Every photo in `data/real/mat/` (file and pixel hashes checked against the sidecars). The kit is applied only where the card stage PASSes. None of these photos shows a Marquis reaction: the lighting and should-fail photos show an orange-red plastic cap, the registration photos an empty zone.');
L.push('');
L.push('| File | Card stage | Sample zone | App says | Reason | Nearest target (ΔE00 / radius) |');
L.push('|---|---|---|---|---|---|');
const references = loadReferences();
const counts: Record<string, number> = {};
for (const path of listPngs('data/real/mat')) {
  const name = parseCaptureName(path.split(/[\\/]/).pop()!);
  const c = await loadCapture(path);
  if (c.fileHashMatches !== true || c.pixelHashMatches !== true) throw new Error(`${path}: hashes do not match its sidecar`);
  const a = analyseMat(c.image, { references });
  const file = relative('data/real/mat', path).replace(/\\/g, '/');
  if (a.verdict !== 'PASS') {
    L.push(`| ${file} | RETAKE (${a.reason}) | not read | RETAKE | ${a.reason} | — |`);
    counts.RETAKE = (counts.RETAKE ?? 0) + 1;
    continue;
  }
  const s = readSampleZone(c.image, a);
  const k = classify(profile, s);
  counts[`${name?.tag === 'registration' ? 'registration' : 'cap'} → ${k.verdict}`] = (counts[`${name?.tag === 'registration' ? 'registration' : 'cap'} → ${k.verdict}`] ?? 0) + 1;
  L.push(`| ${file} | PASS | ${s.status === 'found' ? `coloured region, ${f1(s.areaMm2)} mm², corrected ${lab(s.correctedLab)}` : s.status === 'none' ? 'no coloured region' : `RETAKE (${s.reason})`} | **${k.verdict}** | ${k.reason} | ${k.nearest ? `${k.nearest.label}: ${f1(k.nearest.deltaE00)} / ${f1(k.nearest.radius)}` : '—'} |`);
}
L.push('');
L.push(`Summary: ${Object.entries(counts).map(([k, v]) => `${k}: ${v}`).join('; ')}.`);
L.push('');
L.push('Expected: empty-zone registration photos → NEGATIVE (no colour developed; in the app the officer must also tick that the test is in the zone); accepted cap photos → INCONCLUSIVE (the cap matches no opiate colour). The photos that fail the card stage are never classified.');
L.push('');

L.push('## 2. Published colours');
L.push('');
L.push('### Targets (POSITIVE)');
L.push('');
L.push('| Target | NIJ Table 1 row | Munsell | CIELAB (D65) | Radius ΔE00 | = chip term + correction-error term |');
L.push('|---|---|---|---|---|---|');
for (const t of targets) L.push(`| ${t.label} | ${t.sourceRow} | ${t.notation} | ${lab(t.lab)} | ${t.radius.toFixed(2)} | ${t.radiusDerivation.chipTerm.toFixed(2)} (${t.radiusDerivation.chips.map((c) => `${c.notation} ${c.deltaE00.toFixed(2)}`).join(', ')}) + ${t.radiusDerivation.correctionErrorTerm.toFixed(2)} |`);
L.push('');
L.push(`Radius rule: ${targets[0].radiusDerivation.rule}. Chosen by the user on 2026-09-28 (hue and chroma neighbours only, as NIJ §4.6 matches on hue and saturation; registration photos left out of the correction-error term because they built the reference). Opium (10R 3/2) was left out as a target because it overlaps the non-target reactions of Dristan (2.5 ΔE00 away) and sugar.`);
L.push('');
L.push('### Each non-target reaction against each target (ΔE00; **bold** = inside that target radius)');
L.push('');
L.push(`| Non-target (NIJ Table 1, reagent A.5) | Munsell | ${targets.map((t) => `${t.id} (r ${t.radius.toFixed(1)})`).join(' | ')} | Known false positive? |`);
L.push(`|---|---|${targets.map(() => '---').join('|')}|---|`);
for (const n of profile.knownNonTargetReactions) {
  if (!n.lab) {
    L.push(`| ${n.analyte} | ${n.notation ?? '—'} | ${targets.map(() => '—').join(' | ')} | not converted: ${n.note} |`);
    continue;
  }
  const cells = targets.map((t) => {
    const d = ciede2000(n.lab!, t.lab);
    return d <= t.radius ? `**${d.toFixed(1)}**` : d.toFixed(1);
  });
  L.push(`| ${n.analyte}${n.note ? ` (${n.note})` : ''} | ${n.notation} | ${cells.join(' | ')} | ${n.insidePositiveRadius ? '**yes** — a colour this close would read POSITIVE' : 'no'} |`);
}
L.push('');
L.push('Presumptive colour tests have known false positives: other substances give similar colours with the same reagent. The ones flagged here are expected to read POSITIVE on this app too. That is why the result is presumptive and needs laboratory confirmation.');
L.push('');

// ---------- synthetic ----------
L.push('## 3. SYNTHETIC check (rendered images, not evidence about phones or reactions)');
L.push('');
L.push('A card is rendered in software with a 16 mm matte square of the published colour in the sample zone, "photographed" through a warm colour cast, a tone curve and perspective, and run through the whole app pipeline (card detection, correction against a synthetic registration, sample reading, this profile). This checks the software path only.');
L.push('');
const W = 720;
const H = 960;
const CARD = 500;
const warm: Mat3 = [
  [1.1, 0.04, 0.0],
  [0.02, 0.92, 0.03],
  [0.0, 0.06, 0.65],
];
const perPhoto = [1, 2, 3].map((seed) => {
  const a = analyseMat(renderPhoto(placement(W, H, CARD, 0), { copy: 'A', camera: { noise: 2, seed, exposure: 0.9 } }), { guidanceOnly: true });
  if (!a.patches) throw new Error('synthetic registration failed');
  return Object.fromEntries(a.patches.map((p) => [p.id, p.flat])) as Record<string, Vec3>;
});
const cr = combineRegistration(perPhoto);
const synthRef: MatReference = { schema: REFERENCE_SCHEMA, matVersion: 1, copy: 'A', createdAt: '2026-01-01T00:00:00.000Z', phones: ['synthetic'], note: 'SYNTHETIC, validate-kit only', sources: [], patches: cr.patches, maxSpreadDeltaE00: cr.maxSpread, maxSpreadPatch: cr.maxSpreadPatch, pipeline: { commit: 'synthetic' } };
const synthCases: { what: string; notation: string; lab: Vec3 }[] = [
  ...targets.map((t) => ({ what: `target: ${t.label}`, notation: t.notation, lab: t.lab })),
  ...profile.knownNonTargetReactions.filter((n) => n.lab).map((n) => ({ what: `non-target: ${n.analyte}`, notation: n.notation!, lab: n.lab! })),
];
L.push('| Rendered colour | Munsell | Published CIELAB | Rendered (sRGB-rounded) CIELAB | App reads (corrected) | Read error ΔE00 | App says | Reason |');
L.push('|---|---|---|---|---|---|---|---|');
let seed = 20;
for (const sc of synthCases) {
  const { rgb, clipped } = labToSrgb8(sc.lab);
  const truth = srgb8ToLab(rgb);
  const img = renderPhoto(placement(W, H, CARD, 180, 0.04), {
    marks: [{ shape: 'rect', cx: 52.5, cy: 73, w: 16, h: 16, colour: rgb }],
    camera: { matrix: warm, curve: (x) => Math.pow(x, 0.8), exposure: 0.85, noise: 2, seed: seed++ },
  });
  const a = analyseMat(img, { references: { A: synthRef } });
  if (a.verdict !== 'PASS') {
    L.push(`| ${sc.what} | ${sc.notation} | ${lab(sc.lab)} | ${lab(truth)} | card RETAKE | | RETAKE | ${a.reason} |`);
    continue;
  }
  const s = readSampleZone(img, a);
  const k = classify(profile, s);
  L.push(`| ${sc.what} | ${sc.notation} | ${lab(sc.lab)} | ${lab(truth)}${clipped ? ' (clipped to sRGB)' : ''} | ${lab(s.correctedLab)} | ${s.correctedLab ? f1(ciede2000(s.correctedLab, truth)) : '—'} | **${k.verdict}** | ${k.reason} |`);
  console.log(sc.what, k.verdict);
}
L.push('');
L.push('## Plain limits');
L.push('');
L.push('- **POSITIVE has not been tested on a real reaction.** It appears above only on rendered images. No stand-in object may be used to fake a POSITIVE in a demo.');
L.push('- The target colours are Munsell notations published by NIJ in 2000 (the colour of each reaction as seen against Munsell chips), converted to CIELAB. They were never measured through this app, this card or these phones.');
L.push('- **The absolute accuracy of our correction is unknown**, because the card is calibrated against our own print (registered on one phone at dusk), not against a measured colour standard. The correction-error term in the radius is the leave-one-out error on 3 real photos of one object on one phone.');
L.push('- NEGATIVE means only that no colour developed in the sample zone. The app cannot tell that from an empty zone; the officer must confirm the test is in the zone, and the signed photo shows which it was.');
L.push('- A real deployment needs NCB’s forensic laboratory to photograph real Marquis reactions (each drug, several amounts, several phones and lights) on the registered card with this app, and to replace these numbers with the measured spread (then `validation` becomes `validated-on-real-photos`).');
writeFileSync(OUT, L.join('\n') + '\n');
console.log(`Wrote ${OUT}`);
