// Real-photo check of the sample-zone reader: runs the full card pipeline and
// then readSampleZone on every capture in data/real/mat/, and writes
// docs/validation/sample_zone_v1.md.
//
//   node scripts/validate-sample.ts
//
// Photos are read only through the pixel-contract path; a hash mismatch aborts.

import { execSync } from 'node:child_process';
import { existsSync, readdirSync, writeFileSync } from 'node:fs';
import { join, relative } from 'node:path';
import { analyseMat } from '../src/pipeline/analyse.ts';
import { ciede2000 } from '../src/pipeline/ciede2000.ts';
import { THRESHOLDS } from '../src/pipeline/config.ts';
import { labOfLinear } from '../src/pipeline/correct.ts';
import type { Vec3 } from '../src/pipeline/colour.ts';
import { readSampleZone, type SampleReading } from '../src/pipeline/samplezone.ts';
import { parseCaptureName } from '../src/io/dataset.ts';
import { loadCapture } from './lib/capture-files.ts';
import { loadReferences } from './lib/references.ts';

const DIR = 'data/real/mat';
const OUT = 'docs/validation/sample_zone_v1.md';
const OBJECT = 'an orange-red plastic cap, about 5 cm across and slightly glossy (no orange card strip was available)';

function listPngs(dir: string): string[] {
  if (!existsSync(dir)) return [];
  const out: string[] = [];
  for (const e of readdirSync(dir, { withFileTypes: true })) {
    const p = join(dir, e.name);
    if (e.isDirectory()) out.push(...listPngs(p));
    else if (e.name.endsWith('.png')) out.push(p);
  }
  return out.sort();
}

const fmt = (v: Vec3 | undefined) => (v ? v.map((x) => x.toFixed(1)).join(', ') : '—');
const references = loadReferences();

interface Row {
  file: string;
  tag: string;
  phone: string;
  card: string;
  looMean?: number;
  s?: SampleReading;
  ms?: number;
}
const rows: Row[] = [];
for (const path of listPngs(DIR)) {
  const name = parseCaptureName(path.split(/[\\/]/).pop()!);
  if (!name) throw new Error(`Unexpected file name ${path}`);
  const c = await loadCapture(path);
  if (c.fileHashMatches !== true || c.pixelHashMatches !== true) throw new Error(`${path}: hashes do not match its sidecar; refusing to validate altered data`);
  const a = analyseMat(c.image, { references });
  const row: Row = { file: relative(DIR, path).replace(/\\/g, '/'), tag: name.tag, phone: name.phone, card: a.verdict === 'PASS' ? 'PASS' : `RETAKE (${a.reason})` };
  if (a.verdict === 'PASS') {
    const t0 = performance.now();
    row.s = readSampleZone(c.image, a);
    row.ms = performance.now() - t0;
    row.looMean = a.correction?.used.loo.mean;
  }
  rows.push(row);
  console.log(`${row.file}: card ${row.card}${row.s ? ` -> sample ${row.s.status} ${row.s.reason} (${row.ms!.toFixed(0)} ms)` : ''}`);
}

const commit = (() => {
  try {
    return execSync('git rev-parse --short=12 HEAD', { stdio: ['ignore', 'pipe', 'ignore'] }).toString().trim();
  } catch {
    return 'uncommitted';
  }
})();

const passed = rows.filter((r) => r.s);
const L: string[] = [];
L.push('# Sample zone reading — real-photo check');
L.push('');
L.push(`Generated by \`scripts/validate-sample.ts\` at commit \`${commit}\` on ${new Date().toISOString().slice(0, 10)}.`);
L.push('Every row is a **real photo** from `data/real/mat/` (hashes checked against the sidecars). The reader runs only on photos whose card stage PASSes; the rest are listed for completeness.');
L.push('');
L.push(`Object in the sample zone of the lighting and should-fail photos: ${OBJECT}. The registration photos show an empty zone.`);
L.push('');
L.push('Scope: a test lying in the sample zone (spot, strip, swab, pouch). Liquid in a glass and live guidance for the sample are not built.');
L.push('');
L.push('## Per photo');
L.push('');
L.push(
  `Coloured pixel = ΔE76 from this photo's paper white above ${THRESHOLDS.sampleWhiteNoiseFactor.value} × the white-paper noise (95th percentile over the white patches' pixels), at least ${THRESHOLDS.sampleMinDeltaE.value}. Areas are after a ${THRESHOLDS.sampleEdgeErodeMm.value} mm edge trim. Spread = 90th percentile ΔE76 of the sampled pixels from their median (limit ${THRESHOLDS.maxSampleSpreadDeltaE.value}).`,
);
L.push('');
L.push('| File | Card stage | Sample result | White noise → threshold (ΔE76) | Regions (mm², largest first) | Sampled mm² / px | Clipped in region | Spread | Touches zone edge | CIELAB before | CIELAB after | Time (ms) |');
L.push('|---|---|---|---|---|---|---|---|---|---|---|---|');
for (const r of rows) {
  const s = r.s;
  if (!s) {
    L.push(`| ${r.file} | ${r.card} | not read | | | | | | | | | |`);
    continue;
  }
  L.push(
    `| ${r.file} | PASS | ${s.status === 'found' ? 'coloured region found' : s.status === 'none' ? 'no coloured region' : `RETAKE (${s.reason})`} | ${s.threshold.whiteNoise.toFixed(2)} → ${s.threshold.deltaE.toFixed(1)} | ${s.regions.map((g) => g.areaMm2.toFixed(0)).join(', ') || '—'} | ${s.areaMm2 ? `${s.areaMm2.toFixed(0)} / ${s.pixels}` : '—'} | ${(s.clipFraction * 100).toFixed(1)}% | ${s.spread ? s.spread.toFixed(1) : '—'} | ${s.regions.length ? (s.touchesEdge ? 'yes' : 'no') : '—'} | ${fmt(s.observedLab)} | ${fmt(s.correctedLab)} | ${r.ms!.toFixed(0)} |`,
  );
}
L.push('');

const caps = passed.filter((r) => r.tag !== 'registration' && r.s!.correctedLab && r.s!.observedLab);
L.push('## The cap across the accepted photos');
L.push('');
if (caps.length >= 2) {
  let before = 0;
  let after = 0;
  let camera = 0;
  const cam = (r: Row) => labOfLinear(r.s!.flatLinear!);
  for (let i = 0; i < caps.length; i++)
    for (let j = i + 1; j < caps.length; j++) {
      camera = Math.max(camera, ciede2000(cam(caps[i]), cam(caps[j])));
      before = Math.max(before, ciede2000(caps[i].s!.observedLab!, caps[j].s!.observedLab!));
      after = Math.max(after, ciede2000(caps[i].s!.correctedLab!, caps[j].s!.correctedLab!));
    }
  L.push(`Photos with the cap read (any sample status that produced a colour): ${caps.map((c) => c.file).join(', ')}.`);
  L.push('');
  L.push('| | Largest ΔE00 between any two of these photos |');
  L.push('|---|---|');
  L.push(`| Camera colour, flat-fielded only | ${camera.toFixed(2)} |`);
  L.push(`| Before correction (flat-fielded, normalised to its own paper white) | ${before.toFixed(2)} |`);
  L.push(`| After correction (method ${caps[0].s!.method}) | ${after.toFixed(2)} |`);
  L.push('');
  L.push('"Before correction" is normalised to the paper white of each photo, which already removes overall exposure and white balance. The Session 1 report measured the central 24 mm only; this reads the whole coloured region.');
  L.push('');
  L.push('The cap is wider than the sample zone: on the straightened card it overhangs the zone outline on both sides, so the region is cut off by the edge of the read area ("touches zone edge": yes). A real test should lie inside the zone.');
} else L.push(`Fewer than two accepted photos with a cap colour (${caps.length}); no spread can be given.`);
L.push('');
L.push('## Plain limits');
L.push('');
L.push('- These are the only real photos: an orange-red glossy plastic cap, not a reaction. No real reaction has been read.');
L.push('- The registration photos were also used to build the card references, so their empty-zone result is a check of the reader, not of the correction.');
L.push('- The app cannot tell a colourless negative from an empty zone; both are "no coloured region".');
writeFileSync(OUT, L.join('\n') + '\n');
console.log(`\nWrote ${OUT}`);
